name: github pages

on:
  push:
    branches:
      - master
      - test-workflow
  repository_dispatch:
    types: [ push_event ]

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.101.0'
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Npm Install
        run: npm install

      - name: Clone Vault
        uses: actions/checkout@v2
        with:
          repository: aren227/obsidian-public-vault
          path: ./vault

      - name: Install obsidian-export
        run: Invoke-Webrequest -URI "https://github.com/zoni/obsidian-export/releases/download/v22.1.0/obsidian-export_Windows-x64_64.exe" -OutFile "obsidian-export.exe"

      - name: Export ObsidianMD
        run: ./obsidian-export ./vault/ ./content/en/

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public