name: github pages

on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [ push_event ]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Clone Vault
        uses: actions/checkout@v2
        with:
          repository: aren227/obsidian-public-vault
          path: ./vault

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
            components: rustfmt, clippy

      - name: Install obsidian-export
        run: cargo install obsidian-export --root ./obsidian-export

      - name: Export ObsidianMD
        run: ./obsidian-export/bin/obsidian-export ./vault/ ./content/en/

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Npm Install
        run: npm install

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public